# Generated by Django 6.0.1 on 2026-01-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
