# Generated by Django 6.0.1 on 2026-01-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_exercise_reps_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
