# Generated by Django 6.0 on 2026-01-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='TikTok',
            new_name='tikTok',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='X',
            new_name='x',
        ),
    ]