# Generated by Django 6.0 on 2026-01-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_instagram_userprofile_instagram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tikTok',
            new_name='tiktok',
        ),
    ]
