# Generated by Django 6.0.1 on 2026-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_tiktok_userprofile_tiktok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='x',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
