# Generated by Django 6.0.1 on 2026-01-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Choose your gender:', 'Choose your gender:'), ('Male', 'Male'), ('Female', 'Female')], default='CYO', max_length=30),
        ),
    ]
