# Generated by Django 6.0.1 on 2026-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_userprofile_birthday_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('CYO', 'Choose your gender:'), ('male', 'Male'), ('female', 'Female')], default='CYO', max_length=30),
        ),
    ]
