# Generated by Django 6.0.1 on 2026-01-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_has_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_profile',
        ),
    ]
